# Generated by Django 3.2.16 on 2022-12-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='full_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_link',
            field=models.CharField(max_length=10),
        ),
    ]
